CREATE TABLE
    IF
    NOT EXISTS categories (
    id INT PRIMARY KEY, NAME VARCHAR ( 255 ) NOT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );